# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    
- task: DotNetCoreCLI@2
  displayName: '.NET Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: '.NET Test'
  inputs:
    command: test
    projects: '**/*[Tt]est/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk Conn'
    testType: 'app'
    targetFile: 'src/SimpleWeb.sln'
    monitorWhen: 'always'
    failOnIssues: false
    organization: 'lettucebo'

# Whitesource Bolt have license issue, switch to OWASP dependency-check
#- task: WhiteSource Bolt@20
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'

# # OWASP dependency-check
# - task: dependency-check-build-task@6
#   displayName: 'Dependency Check'
#   inputs:
#     projectName: 'Ci.Result'
#     scanPath: '**/*.csproj'
#     format: 'HTML, CSV, JSON, JUNIT'

# # Publish OWASP dependency-check report
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'dependency-check/*junit.xml'
#     searchFolder: '$(Common.TestResultsDirectory)'
