variables:
  - name: random
    value: jsniwa
stages:
  - stage: Infra
    displayName: SimpleWeb.Infra
    jobs:
      - job: Agent_job
        displayName: Agent job
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Replace tokens in **/*.tf
            inputs:
              rootDirectory: $(System.DefaultWorkingDirectory)/_SimpleWeb.Publish/drop/tf
              targetFiles: "**/*.tf"
              escapeType: none
              tokenPrefix: __
              tokenSuffix: __
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: "Terraform : init"
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/_SimpleWeb.Publish/drop/tf
              backendServiceArm: xxxxxxxx-4067-4e0e-974f-640b2b24997d
              backendAzureRmResourceGroupName: Demo1123
              backendAzureRmStorageAccountName: demotf1125
              backendAzureRmContainerName: terraform
              backendAzureRmKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: "Terraform : azurerm"
            inputs:
              command: apply
              workingDirectory: $(System.DefaultWorkingDirectory)/_SimpleWeb.Publish/drop/tf
              commandOptions: --auto-approve
              environmentServiceNameAzureRM: xxxxxxxx-4067-4e0e-974f-640b2b24997d
  - stage: Deploy
    displayName: SimpleWeb.Infra
    jobs:
      - job: Agent_job
        displayName: Agent job
        steps:
          - task: AzureWebApp@1
            displayName: "Azure Web App Deploy: web$(random)"
            inputs:
              azureSubscription: xxxxxxxx-4067-4e0e-974f-640b2b24997d
              appType: webAppLinux
              appName: web$(random)
