name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run tests
        run: dotnet test
