name: Build and Test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore "src/SimpleWeb.sln"

      - name: Build project
        run: dotnet build "src/SimpleWeb.sln"

      - name: Run tests
        run: dotnet test "src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj"
