name: Build and Test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.1
      - name: echo info
        run: |
          echo "EVENT $GITHUB_EVENT_NAME"
          echo "REF: $GITHUB_REF"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore "src/SimpleWeb.sln"
      - name: Build project
        run: dotnet build "src/SimpleWeb.sln"
      - name: Run tests
        run: dotnet test "src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj"

