name: Release
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore "src/SimpleWeb.sln"
      - name: Publish project
        run: dotnet publish "src/SimpleWeb/SimpleWeb.csproj" -c Release -o "src/SimpleWeb/bin/Release/net6.0/publish"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simpleweb
          path: src/SimpleWeb/bin/Release/net6.0/publish
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simpleweb
          path: deploy/simpleweb
